### ISSUE TITLE
Reqwest vs Curl

### ISSUE THREAD

**Issue by mitchmindtree** [freesig/moltenvk_deps#1]
Using reqwest is a really cool idea! Probably much more cross platform than relying on curl bindings as everything gets built from pure rust src.

That said, this will only be used on Mac, and I wonder if it's worth the difference in compile time? Building reqwest also means building hyper and all its deps, but I forget how long it takes to build hyper.

What issues exactly were you running into with curl out of curiosity?

**Comment by freesig** [comment]
Curl would randomly stop the download when it was incomplete but it's possible that I wasn't using it correctly. It also wouldn't emit an error so I couldn't tell the download had failed. When I searched for Rust download files everyone just said to use reqwest.

Is there anything in the nannou chain that already uses reqwest? Because then we should already have it but if not yeh it's a little annoying to compile it just for this.
I wish there was a way to not compile the dependencies (ie. reqwest) if the `VULKAN_SDK` is set.

I can play around with curl a bit more and see if I can get it working though.

**Comment by freesig** [comment]
curl support added
